\input texinfo                @c -*- Texinfo -*-
@c %**start of header
@setfilename sysadmin-france.info
@settitle @code{System Administration France}
@setchapternewpage odd
@c %**end of header

@set RCSID $Id: sysadmin-france.en.texi,v 1.2 2001-04-16 20:35:55 loic Exp $
@set VERSION 1.0

@c Combine the variable and function indices:
@syncodeindex vr fn
@c Combine the program and concept indices:
@syncodeindex pg cp

@titlepage
@title System Administration France
@subtitle Information specific to GNU and FSF machines in France
@subtitle @code{Sysadmin France} Version @value{VERSION}
@author Loic Dachary
@page
@vskip 0pt plus 1filll

 Permission is granted to make and distribute verbatim copies of
 this manual provided the copyright notice and this permission notice
 are preserved on all copies.

 Permission is granted to copy and distribute modified versions of this
 manual under the conditions for verbatim copying, provided that the entire
 resulting derived work is distributed under the terms of a permission
 notice identical to this one.

 Permission is granted to copy and distribute translations of this manual
 into another language, under the above conditions for modified versions,
 except that this permission notice may be stated in a translation approved
 by the Free Software Foundation.
@end titlepage
@page

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Sysadmin France

This document is for system administrators, webmasters and users of GNU
and FSF machines in France.

@end ifnottex

@menu
* Introduction::                
* Accounts::                    
* Web::                         
* Concept Index::               
* Name Index::                  

@detailmenu
 --- The Detailed Node Listing ---

Accounts

* Account Create::              
* Account Access::              
* Account Update::              
* Account Delete::              
* Cron Job::                    

Web

* Overview::                    
* Update from CVS::             
* Nightly script::              

@end detailmenu
@end menu

@node Introduction, Accounts, Top, Top
@chapter Introduction

No information on the philosophical and political goals of the
@uref{http://www.fsfeurope.org/,,FSF Europe} in general and the
@uref{http://france.fsfeurope.org/,,FSF France} in particular can be
found in this document. 

The machines donated to FSF France and hosted in France are part of the
set of machines available to the GNU project. As such they follow the
same rules and the same policy.

In many aspects, the GNU way of doing things needs to be improved. When
this is the case the idea is to coordinate with the GNU volunteers in
charge of a specific aspect in order to improve the system. Doing so is
a lot easier than contributing to a software. It may sometime be
furstrating to stick to the GNU policy because it is easier to have a
quick and nice result by inventing something completly new. The Web is
probably the most striking example. However, since we claim to be part
of the GNU project we don't really have the option to fork something of
our own and leave the GNU project behind. Even if it means that we will
go slower, coordination with and improvement of the GNU project as a
whole should be our goal.

Close cooperation with the GNU project also makes some things a lot
easier. The account creation process, the management of the HTML tree
from CVS, the DNS hosting, mailing lists etc. are facilities we do not
need to re-implement. When installing something entirely new on the FSF
France machines, it is important to send a note on the relevant mailing
lists in advance. This prevents possible duplication of the effort and
greatly increases the chances that the GNU project will be able to
re-use the new facility.

Reference documents describing the GNU environment are
@uref{http://www.gnu.org/server/standards/,,standards} for webmaster
information, @file{fencepost.gnu.org:/gd/gnuorg/sysadmin/sysadmin.texi}
for system administration information and the
@uref{http://savannah.gnu.org/savannah.html,,Savannah admin guide} for
usage of the SourceForge clone.

@node Accounts, Web, Introduction, Top
@chapter Accounts

@menu
* Account Create::              
* Account Access::              
* Account Update::              
* Account Delete::              
* Cron Job::                    
@end menu

@node Account Create, Account Access, Accounts, Accounts
@section Account Create

@cindex shell account
@cindex fsffr and shell account

The user accounts on @code{france.fsfeurope.org} are managed with
@uref{http://savannah.gnu.org/,,Savannah}. If someone need a shell
account on @code{france.fsfeurope.org} he has to get an account on
@uref{http://savannah.gnu.org/,,Savannah} first. Then he should send
a mail to one of the project administrators of the 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr} project. The
project administrator adds him as a member of the 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr} project. Within
24 hours a cron job on @code{france.fsfeurope.org} will fetch the
new user from Savannah and create the account. 

@node Account Access, Account Update, Account Create, Accounts
@section Account Access

@cindex shell account ssh
@cindex ssh shell account
@cindex ssh public key
@cindex password ssh
@cindex ssh and password 
Once the account is created, access to the machine is available using
ssh and a public key. The Savannah password will not work on 
@code{france.fsfeurope.org}. When logged on 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr} it is possible
to register one or more public key at 
@uref{http://savannah.gnu.org/account/editsshkeys.php,,Edit SSH Keys}. 

@node Account Update, Account Delete, Account Access, Accounts
@section Account Update

@cindex public key update
@cindex ssh public key update
Once a day the ssh public keys of every account on
@code{france.fsfeurope.org} are updated from the information fetched on
Savannah. If the @file{authorized_keys} file of a user is manualy updated,
it will be overwritten. 

@node Account Delete, Cron Job, Account Update, Accounts
@section Account Delete

When a user is not listed anymore in the 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr}, its account is
disabled on @code{france.fsfeurope.org}. The home directory is not 
deleted and if the user is added again at a later time, he will retrieve
his former home directory. 

@node Cron Job,  , Account Delete, Accounts
@section Cron Job

The @file{/usr/local/bin/savannah_users} script does the update. It
is run from the @file{/etc/cron.d/savannah_users} cron file and spits
log information in @file{/var/log/savannah_users.log}. The log file
is rotated according to the @file{/etc/logrotate.d/savannah_users}
specification.

Savannah does not serve account information anonymously. The 
@code{france.fsfeurope.org} machine is explicitly allowed to retrieve
the relevant information in XML. For more information check the
@uref{http://savannah.gnu.org/savannah.html#Account%20Management,,Account Management} chapter of the Savannah documentation.

@node Web, Concept Index, Accounts, Top
@chapter Web

@menu
* Overview::                    
* Update from CVS::             
* Nightly script::              
@end menu

@node Overview, Update from CVS, Web, Web
@section Overview

All users registered in the
@uref{http://savannah.gnu.org/projects/fsfe/,,FSF Europe} project can
edit the HTML repository using CVS/SSH.

The @code{www} user owns the web directory. The document root is 
@file{/var/www/} that is a link to @file{/home/www/fsfe/fr}. The web
site itself is an anonymous checkout of the @file{fr} directory of the
@uref{http://www.fsfeurope.org/,,FSF Europe} HTML repository. 

@node Update from CVS, Nightly script, Overview, Web
@section Update from CVS

The checkout is updated every hour by the @file{/etc/cron.d/www} user crontab. 
The logs of the checkout are stored in @file{/var/log/www.log} and rotated
by @file{/etc/logrotate.d/www}. 

@node Nightly script,  , Update from CVS, Web
@section Nightly script

The @file{/home/www/bin/nightly} script is run daily and is in charge of
the following:

@itemize @bullet

@item Update the symbolic links according to the content of the
@file{.symlinks} files. See the @uref{http://www.gnu.org/server/standards/README.html#SEC01,,Symbolic Links} chapter of the webmaster guidelines for
detailed information.

@item Run the @code{all} goal for each Makefile in the directory tree. For
instance, if @code{about/Makefile} exists, then @code{make -C about all} is
run. 

@end itemize

The logs of the nightly script are stored in @file{/var/log/nightly.log}
and rotated by @file{/etc/logrotate.d/nightly}.

@node Concept Index, Name Index, Web, Top
@unnumbered Index of Concepts

@printindex cp

@node Name Index,  , Concept Index, Top
@unnumbered Index of File Names

@printindex fn

@summarycontents
@contents
@bye

