\input texinfo                @c -*- Texinfo -*-
@c %**start of header
@setfilename sysadmin-france.info
@settitle @code{System Administration France}
@setchapternewpage odd
@c %**end of header

@set RCSID $Id: sysadmin-france.en.texi,v 1.58 2002-04-01 00:47:43 loic Exp $
@set VERSION 1.0

@c Combine the variable and function indices:
@syncodeindex vr fn
@c Combine the program and concept indices:
@syncodeindex pg cp

@titlepage
@title System Administration France
@subtitle Information specific to GNU and FSF machines in France
@subtitle @code{Sysadmin France} Version @value{VERSION}
@author Loic Dachary, Rodolphe Quiedeville, Cyril Bouthors
@page
@vskip 0pt plus 1filll

 Permission is granted to make and distribute verbatim copies of
 this manual provided the copyright notice and this permission notice
 are preserved on all copies.

 Permission is granted to copy and distribute modified versions of this
 manual under the conditions for verbatim copying, provided that the entire
 resulting derived work is distributed under the terms of a permission
 notice identical to this one.

 Permission is granted to copy and distribute translations of this manual
 into another language, under the above conditions for modified versions,
 except that this permission notice may be stated in a translation approved
 by the Free Software Foundation.
@end titlepage
@page

@ifnottex
@node Top, Introduction, (dir), (dir)
@top Sysadmin France

This document is for system administrators, webmasters and users of GNU
and FSF machines in France.

@end ifnottex

@menu
* Introduction::                
* Hardware List::               
* Hardware Setup::              
* Accounts::                    
* System::                      
* Concept Index::               
* Name Index::                  

@detailmenu
 --- The Detailed Node Listing ---

Accounts

* System Passwords::            
* Account Create::              
* Account Access::              
* Account Update::              
* Account Delete::              
* Account www::                 
* Cron Job::                    

System

* Security alert::              
* Hosting facilities::          
* Security::                    
* DNS::                         
* Statistics::                  

Security

* Firewall::                    

Statistics

* Installation::                
* Output::                      

@end detailmenu
@end menu

@node Introduction, Hardware List, Top, Top
@chapter Introduction

No information on the philosophical and political goals of the
@uref{http://www.fsfeurope.org/,,FSF Europe} in general and the
@uref{http://france.fsfeurope.org/,,FSFE France} in particular can be
found in this document. 

The machines donated to the FSF Europe and hosted in France are part
of the set of machines available to the GNU project. As such they
follow the same rules and the same policy.

Reference documents describing the GNU environment are
@file{fencepost.gnu.org:/gd/gnuorg/sysadmin/sysadmin.texi}
for system administration information and the
@uref{http://savannah.gnu.org/savannah.html,,Savannah admin guide} for
usage of the project hosting facility.

@node Hardware List, Hardware Setup, Introduction, Top
@chapter Hardware List

This list accurately describes the purpose of each piece of
harware dedicated to the GNU project in France. It must not
describe the interconnection between them. If something is
running on these machines that do not match the intented
purpose described here, it can be uninstalled without notice.

@itemize

@item UPS x 3

Contact : @email{loic@@gnu.org,Loic Dachary}, @email{valignat@@nevrax.org,Cedric Valignat}

@item fr.fsf.org

Web hosting (www.fsfeurope.org, france.fsfeurope.org); Secondary
DNS for GNU (ns2.gnu.org); GNU Friends hosting.

@example
PIII500, 512Mb RAM, 5x9Gb SCSI
@end example

Contact : @email{loic@@gnu.org,Loic Dachary}, @email{valignat@@nevrax.org,Cedric Valignat}

@item snail.gnu.org

Savannah mirror; Audio/Video gatekeeper (gnomemeeting relay);

@example
Dual PIII 550
1 GB RAM
Asus P2B-D
2 serial ports
1 parallel port
2 ethernet 3c905C-TX
2 20 GB IDE disks
1 SCSI Adaptec 7892A (rev 02)
Double power
@end example

Contact : @email{cyril@@bouthors.org,Cyril Bouthors}, @email{rq@@lolix.org,Rodolphe Quiedeville}, @email{jlb@@j1b.org,Jean-Louis Bergamo}, @email{loic@@gnu.org,Loic Dachary}

@item frog.gnu.org

Serial console server. 

@example
PII 350
256 MB RAM
Asus P2B-D
2 serial ports
1 parallel port
1 ethernet 3c905C-TX
2 20 GB IDE disks
Double power
@end example

Contact : @email{cyril@@bouthors.org,Cyril Bouthors}, @email{rq@@lolix.org,Rodolphe Quiedeville}, @email{jlb@@j1b.org,Jean-Louis Bergamo}, @email{loic@@gnu.org,Loic Dachary}

@item Cisco Catalyst 3500 XL

Typical session:

@example
switch> enable
Password:
switch# show configuration (show kind of a diff with the defaults)
switch# configure terminal
switch(config)# exit
switch# write memory
switch# exit
@end example

It is only possible to get access to the switch from the serial line.

The SNMP server was configured and is available with the 
GnuRms community.

Documents : @uref{http://www.cisco.com/warp/public/cc/pd/si/casi/ca3500xl/prodlit/index.shtml,,Product description},
@uref{http://www.cisco.com/univercd/cc/td/doc/product/lan/c2900xl/29_35wc/index.htm,,Product manual}

Contact : @email{jlb@@j1b.org,Jean-Louis Bergamo}, @email{loic@@gnu.org,Loic Dachary}

@item BlackBox Pow-R-Boot 5 +

Documents : @uref{http://catalog.blackbox.com/BlackBox/templates/blackbox/itemgroup1015guest.asp?param=272&ig_id=1015&title=Pow%2DR%2DBoot+5&related=,,Product manual}

Contact : @email{loic@@gnu.org,Loic Dachary}

@item Blackbox ServSwitch

5 ports.

Documents : @uref{http://catalog.blackbox.com/BlackBox/templates/blackbox/itemgroup2590guest.asp?param=539&ig_id=2590&title=Matrix+ServSwitch&related=,,Product manual}

Contact : @email{loic@@gnu.org,Loic Dachary}

@item Desktop

Not available on the Internet. Dedicated to office needs of
FSFE France.

@example
Dual PIII 500
512Mb RAM
4G SCSI
8G IDE
CD PLEXTOR 32X
CD TEAC CD-R55S
ATI Mach64
Voodoo 2
AWE 64 gold
IIyama 17"
@end example

Contact : @email{loic@@gnu.org,Loic Dachary}, @email{rq@@lolix.org,Rodolphe Quiedeville}, @email{guerby@@acm.org,Laurent Guerby}

@item Laptop

Not available on the Internet. Dedicated to Frederic Couchet for
permanent activism.

@example
Inspiron 3500
128Mb RAM
6G Disk
@end example

@end itemize

@node Hardware Setup, Accounts, Hardware List, Top
@chapter Hardware Setup

Each hardware is mentionned by its name in the @xref{Hardware List}.
Each location is mentionned by its name in the @xref{Hosting
facilities}.  The sole purpose of this chapter is to describe the
precise location of the corresponding hardware and its physical
connections with other hardware.

@itemize @bullet

@item

snail.gnu.org is hosted at Free.

@example
ttyS0 = snail.gnu.org:/dev/ttyS0 -> Cisco Catalyst 3500 XL:console : 9600 8N1, 
	cisco specific cable (flat blue rj45 + db9 adaptator ref 74-0495-01 written on it)
ttyS1 = frog.gnu.org:/dev/ttyS1 -> snail.gnu.org:/dev/ttyS1 (getty) : 9600 8N1, null modem db9
power cable is controled by BlackBox Pow-R-Boot 5 +
ethernet cable is connected to Cisco Catalyst 3500 XL
@end example

@item

frog.gnu.org is hosted at Free.

@example
ttyS0 = frog.gnu.org:/dev/ttyS0 -> BlackBox Pow-R-Boot 5 +:console : 9600 8N1, null modem db9
ttyS1 = frog.gnu.org:/dev/ttyS1 -> snail.gnu.org:/dev/ttyS1 (getty) : 9600 8N1, null modem db9
power cable is controled by BlackBox Pow-R-Boot 5 +
ethernet cable is connected to Cisco Catalyst 3500 XL
@end example

@item

Cisco Catalyst 3500 XL is hosted at Free.

@example
snail.gnu.org:/dev/ttyS0 -> Cisco Catalyst 3500 XL:console : 9600 8N1, 
	cisco specific cable (flat blue rj45 + db9 adaptator ref 74-0495-01 written on it)
@end example

@item

BlackBox Pow-R-Boot 5 + is hosted at Free.

@example
frog.gnu.org:/dev/ttyS0 -> powerboot:console : 9600 8N1, null modem db9
@end example

@item 

Blackbox ServSwitch is hosted at Free.

@item

fr.fsf.org is hosted at Nevrax.

@example
fr.fsf.org power cable is connected to a UPS
@end example

@item

UPS x 3 are hosted at Nevrax.

@item

Desktop is hosted at Lolix.

@item

Laptop is travelling with Frederic Couchet.

@end itemize

@node Accounts, System, Hardware Setup, Top
@chapter Accounts

@menu
* System Passwords::            
* Account Create::              
* Account Access::              
* Account Update::              
* Account Delete::              
* Account www::                 
* Cron Job::                    
@end menu

@node System Passwords, Account Create, Accounts, Accounts
@section System Passwords

If you need the password of system users such as root or www you
should ask to the following persons:

@itemize

@item @email{rq@@lolix.org,Rodolphe Quiedeville}

@item @email{loic@@gnu.org,Loic Dachary}

@item @email{jlb@@j1b.org,Jean-Louis Bergamo}

@item @email{cyril@@bouthors.org,Cyril Bouthors}

@end itemize

@node Account Create, Account Access, System Passwords, Accounts
@section Account Create

@cindex shell account
@cindex fsffr and shell account

The user accounts on @code{france.fsfeurope.org} are managed with
@uref{http://savannah.gnu.org/,,Savannah}. If someone need a shell
account on @code{france.fsfeurope.org} he has to get an account on
@uref{http://savannah.gnu.org/,,Savannah} first. Then he should send
a mail to one of the project administrators of the 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr} project. The
project administrator adds him as a member of the 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr} project. Within
24 hours a cron job on @code{france.fsfeurope.org} will fetch the
new user from Savannah and create the account. 

@node Account Access, Account Update, Account Create, Accounts
@section Account Access

@cindex shell account ssh
@cindex ssh shell account
@cindex ssh public key
@cindex password ssh
@cindex ssh and password 
Once the account is created, access to the machine is available using
ssh and a public key. The Savannah password will not work on 
@code{france.fsfeurope.org}. When logged on 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr} it is possible
to register one or more public key at 
@uref{http://savannah.gnu.org/account/editsshkeys.php,,Edit SSH Keys}. 

@node Account Update, Account Delete, Account Access, Accounts
@section Account Update

@cindex public key update
@cindex ssh public key update
Once a day the ssh public keys of every account on
@code{france.fsfeurope.org} are updated from the information fetched on
Savannah. If the @file{authorized_keys} file of a user is manually updated,
it will be overwritten. 

@node Account Delete, Account www, Account Update, Accounts
@section Account Delete

When a user is not listed anymore in the 
@uref{http://savannah.gnu.org/projects/fsffr/,,fsffr}, its account is
disabled on @code{france.fsfeurope.org}. The home directory is not 
deleted and if the user is added again at a later time, he will retrieve
his former home directory. 

@node Account www, Cron Job, Account Delete, Accounts
@section Account www

Every account created automatically as described above is also granted
an access to the @code{www} user which owns the directory in which all
the document roots of the apache server are : @file{/home/www}.

This is simply done by appending the public keys of all the users to the
@file{authorized_keys} file of the @code{www} user. 

@node Cron Job,  , Account www, Accounts
@section Cron Job

The @file{/usr/local/bin/savannahusers} script does the update. It
is run from the @file{/etc/cron.d/savannahusers} cron file and spits
log information in @file{/var/log/savannahusers.log}. The log file
is rotated according to the @file{/etc/logrotate.d/savannahusers}
specification.

Savannah does not provide account information to non identified
machines. The @code{france.fsfeurope.org} machine is explicitly allowed
to retrieve the relevant information in XML. For more information check
the
@uref{http://savannah.gnu.org/savannah.html#Account%20Management,,Account
Management} chapter of the Savannah documentation.

The @file{savannahusers} script sources can be found in the
@uref{http://savannah.gnu.org/projects/www/,,www} project source tree.
It was checked out in @file{france.fsfeurope.org:/usr/local/src/www}
directory, together with other GNU specific maintainance scripts.

@node System, Concept Index, Accounts, Top
@chapter System

@menu
* Security alert::              
* Hosting facilities::          
* Security::                    
* DNS::                         
* Statistics::                  
@end menu

@node Security alert, Hosting facilities, System, System
@section Security alert

When there is a suspicion that the france.fsfeurope.org machine was
compromised a mail should be sent to @email{france@@fsfeurope.org,FSF
France private mailing list} and the following people can be contacted.

@itemize @bullet

@item @email{igor@@genibel.org,Igor Genibel}. Installed security instrusion
detection tools.

@item @email{jlb@@j1b.org,Jean Louis Bergamo}. Examined and upgraded
the installed packages and carefully removed or replaced those that 
may present security problems.

@item @email{rq@@lolix.org,Rodolphe Quiedeville}. Analysed the logs
for traces of intrusion.

@item @email{valignat@@nevrax.org,Cedric Valignat}. Analysed the logs
for traces of intrusion.

@item @email{loic@@gnu.org,Loic Dachary}. Knows every person who has 
access to the machine.

@end itemize

The intrusion related mails are kept in a private mail archive for
future reference and are listed here.

@itemize @bullet

@item @uref{http://mailman.fsfeurope.org/mailman/private/france/2001-June/000272.html,,June 29}.

@end itemize

@node Hosting facilities, Security, Security alert, System
@section Hosting facilities

@cindex Connection is down
@cindex Colt
@cindex Nevrax

The france.fsfeurope.org machine is hosted by 

@example
Nevrax
104 rue du Fg St Antoine
75011 Paris
+33 1 44 74 83 85
@end example

The leased line that connects Nevrax to the Internet is provided by

@example
COLT Telecommunication
60 rue de Wattignies - Bat. B
75012 PARIS
Email : opi@@fr.colt.net and support@@fr.colt.net
Phone : +33 1 44 29 58 99
Fax   : +33 1 44 29 57 97
@end example

Here is a complete list of the mail threads related to solving problems
when something goes wrong with the Internet connection.

@cindex troubleshooting

@itemize @bullet

@item @uref{http://mail.gnu.org/pipermail/fsfe-france/2001-July/000805.html,,July 14}

@end itemize

Here is a list of people who know some about the machine and its connectivity
and who actually did something in the past to improve or fix it. Feel
free to add yourself if you were forgotten.

@cindex connection trouble contact 
@cindex internet is down
@cindex machine does not respond

@itemize @bullet

@email{valignat@@nevrax.com,Cedric Valignat}
Work: +33 1 42 00 25 57
System administrator who is physically near the machine most of the
time.

@item @email{loic@@gnu.org,Loic Dachary} 
Work: +33 1 41 66 47 22, Home: +33 1 42 45 09 16. 
Asked Nevrax to host the machine. 
Installed the machine. Asked Colt to change the
reverse for fr.fsf.org.

@item @email{cyril@@bouthors.org,Cyril Bouthors}.
Work: +33 1 41 66 47 06.
Monitors the machine. Know Colt
pretty well. Opened trouble tickets when the line was down.

@item @email{rq@@lolix.org,Rodolphe Quiédeville}. 
Work: +33 1 40 15 03 18.
Installed the machine. 
Installed and maintains monitoring tools on fr.fsf.org.

@item @email{devnull@@gnu.org,Joel N. Weber II}. Monitors the machine. Opened
trouble tickets when the line was down. Calculated the reliability of
the Colt connection. 

@end itemize

If the people and contacts listed here are for some reason unable to fix
an urgent problem, one can look into the sysadmin.texi document (entry
@uref{http://www.nevrax.com/,Nevrax}) in the private project
@uref{http://savannah.gnu.org/projects/sysadmin/}. This document list
additional information that cannot be published to preserve the privacy
of the people.

@cindex security
@node Security, DNS, Hosting facilities, System
@section Security

@menu
* Firewall::                    
@end menu

@cindex firewall
@node Firewall,  , Security, Security
@subsection Firewall

A shell script applies filtering rules, it's located in
@file{/etc/init.d/firewall}. This script is compatible with kernel 2.2
and 2.4 and detects the kernel version using @file{uname}. @file{ipchains} is
used with 2.2 and @file{iptables} with 2.4.

Warning : only the ipchains (2.2) section is well configured.

The policy applied is to close all TCP/UDP port by default and open only
the ones we need.

@cindex DNS
@cindex fsffrance.org
@node DNS, Statistics, Security, System
@section DNS

The FSF France machine has a canonical name of @code{fr.fsf.org}, this
name should be used for the reverse.

Unless stated otherwise in the @file{/etc/bind/named.conf} file, all
the domains use @code{ns1.gnu.org} as a primary name server and
@code{ns1.fsffrance.org} as a secondary name server.

@code{ns1.fsffrance.org} is used as a secondary name server for most
Europe related domain names. It should not be used as a primary DNS,
unless someone is willing to take the responsibility of taking care of
it permanently. 

The domain name @code{fsffrance.org} has been bought at
@uref{http://www.gandi.net,,GANDI}, a French registrar, and is owned by
@email{raph@@r4f.org,Raphael Rousseau} who's the Administrative,
Technical and Billing contact of this domain name.

The domain name @code{fsfeurope.org} is owned by @email{greve@@gnu.org,,Georg Greve}.

@cindex statistics mrtg
@node Statistics,  , DNS, System
@section Statistics

Systems statistics are generated with mrtg
@uref{http://ee-staff.ethz.ch/~oetiker/webtools/mrtg/}

@menu
* Installation::                
* Output::                      
@end menu

@node Installation, Output, Statistics, Statistics
@subsection Installation

mrtg and addons have been installed with apt-get, two packages :

@itemize
@item
mrtg version 2.8.9-1
@item
mrtgutils version 0.2
@end itemize

Some more scripts are used, they are located in @file{/usr/local/bin},
they are coming from @uref{http://mrtg.xidus.net/}

@itemize
@item
swapstat.sh
@item
stat.pl
@end itemize


@node Output,  , Installation, Statistics
@subsection Output

Output dir is @file{/var/www/france.fsfeurope.org/mrtg/}

@node Concept Index, Name Index, System, Top
@unnumbered Index of Concepts

@printindex cp

@node Name Index,  , Concept Index, Top
@unnumbered Index of File Names

@printindex fn

@summarycontents
@contents
@bye
