<?php
$subject = 'Kiitos FSFE:n tukemisesta';

$message = '
Kiitos tukesi osoittamisesta FSFE:lle!

Havaitsimme, että sähköpostiosoitettasi on jo käytettu 
tukijaksi ilmoittautumisessa.

Tietosi löytyy sivulta
http://fsfe.org/support/portal?'. $secret_from_db .'

Huomaa että tämä verkkosoite on henkiökohtainen. Voit käyttää
sitä koska tahansa nähdäksesi omat tietosi, ilman että sinun
tarvitsee muistaa mitään erillistä salasanaa.

Kiitos!
';

?>
