<!--<?php
// This is the contents of the e-mail sent to a new signup

$subject = 'Confirm your e-mail address';

$message = '
Thank you for showing your support to the FSFE!

Please confirm your e-mail address by opening the page
http://fsfe.org/support/portal.en?'. $secret .'

Thank you!
';

?>-->

<?php
// This is the contents of the e-mail sent to a new signup

$subject = 'Conferma il tuo indirizzo e-mail';

$message = '
Grazie per aver espresso il tuo sostegno alla FSFE!

Ti preghiamo di confermare il tuo indirizzo e-mail aprendo la pagina
http://fsfe.org/support/portal.it?'. $secret .'

Thank you!
';

?>
