<!--<?php
// This is the HTML contents shown after user submitted the support form

echo '
<p>Thank you for showing your support to the FSFE!</p>
<p>A confirmation message has been sent to your e-mail '. $_POST['email'] .'</p>
';

?>-->





<?php
// This is the HTML contents shown after user submitted the support form

echo '
<p>Grazie per esprimere il tuo sostegno alla FSFE!</p>
<p>Un messaggio di conferma è stato inviato alla tua casella e-mail  '. $_POST['email'] .'</p>
';

?>
