<?php
// This is the contents of the e-mail sent to a signup whos the e-mail was
// already found in the supporter database.

$subject = 'Faleminderit që përkrahni FSFE-në';

$message = '
Faleminderit që demonstroni përkrahjen tuaj për FSFE-në!

Sidoqoftë, kjo adresë e-mail është regjistruar më herët.

Ju lutemi, shihni hollësitë duke hapur faqen
http://fsfe.org/support/portal.sq?'. $secret_from_db .'

Mbani parasysh që kjo URL është personale. Mund ta përdorni
që të hyni te hollësitë tuaja si përkrahës kurdo që dëshironi,
dhe nuk ka fjalëkalim shtesë që ta mbani mend.

Ju faleminderit!
';

?>
