<?php
// This is the contents of the e-mail sent to a new signup

$subject = 'Confirm your e-mail address';

$message = '
Thank you for showing your support to the FSFE!

Please confirm your e-mail address by opening the page
http://fsfe.org/support/portal.en?'. $secret .'

Thank you!

PS: Please do not forward this link to other people. Knowledge of this link
enables any person to change some of your personal settings on the FSFE
website. The link is meant for your eyes only.
';

?>
