<?php
// This is the contents of the e-mail sent to a new signup

$subject = 'Bestätigen Sie Ihre E-Mail-Adresse';

$message = '
Vielen Dank, dass Sie die FSFE unterstützen!

Bitte bestätigen Sie Ihre E-Mail-Adresse durch Aufrufen folgender URL:
http://fsfe.org/support/portal.de?'. $secret .'

Vielen Dank!

PS: Bitte leiten Sie diesen Link nicht an andere Personen weiter. Die
Kenntnis dieses links ermöglicht es jeder beliebigen Person, einige Ihrer
persönlichen Einstellungen auf der FSFE Webseite zu ändern. Der Link ist
nur für Sie gedacht.
';

?>
