---
kind: pipeline
type: docker
name: default

clone:
  depth: 150

steps:
  - name: pre-commit
    image: docker:27.4.1
    environment:
      # Environment variables necessary for rootless Docker
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
    volumes:
      # Mounting Docker socket of rootless docker user
      - name: dockersock
        path: /run/user/1001/docker.sock
    commands:
      - docker ps && echo "tampered with"
      - echo "DRONE_COMMIT_BRANCH ${DRONE_COMMIT_BRANCH}"
      - docker compose --project-name fsfe-website-pre-commit run --remove-orphans --build pre-commit "origin/${DRONE_COMMIT_BRANCH}"

  - name: deploy-master
    image: docker:27.4.1
    environment:
      # Environment variables necessary for rootless Docker
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
      # Target use ipv4 proxies for noddack and gahn, as ipv6 broken.
      TARGET: "www@proxy.noris.fsfeurope.org:fsfe.org/global/?10322,www@proxy.plutex.fsfeurope.org:fsfe.org/global/?10322"
      KEY_PRIVATE:
        from_secret: KEY_PRIVATE
      KEY_PASSWORD:
        from_secret: KEY_PASSWORD
      GIT_TOKEN:
        from_secret: BUILD_TOKEN
      VOLUME: website-cached-master
    volumes:
      # Mounting Docker socket of rootless docker user
      - name: dockersock
        path: /run/user/1001/docker.sock
    commands:
      - docker ps && echo "tampered with"
      # If we are in a cron job, then do a full rebuild
      # Ideally the cron would set the flag itself, but drone does not support that.
      - if [ "$DRONE_BUILD_EVENT" = "cron" ]; then EXTRA_FLAGS="--full"; fi
      - docker compose --project-name fsfe-website-build run --remove-orphans --build build --target "$TARGET" $EXTRA_FLAGS
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request

  - name: deploy-test
    image: docker:27.4.1
    environment:
      # Environment variables necessary for rootless Docker
      XDG_RUNTIME_DIR: "/run/user/1001"
      DOCKER_HOST: "unix:///run/user/1001/docker.sock"
      # Target use ipv4 proxies for noddack and gahn, as ipv6 broken.
      TARGET: "www@proxy.noris.fsfeurope.org:test.fsfe.org/global/?10322,www@proxy.plutex.fsfeurope.org:test.fsfe.org/global/?10322"
      KEY_PRIVATE:
        from_secret: KEY_PRIVATE
      KEY_PASSWORD:
        from_secret: KEY_PASSWORD
      GIT_TOKEN:
        from_secret: BUILD_TOKEN
    volumes:
      # Mounting Docker socket of rootless docker user
      - name: dockersock
        path: /run/user/1001/docker.sock
    commands:
      - docker ps && echo "tampered with"
      # If we are in a cron job, then do a full rebuild
      # Ideally the cron would set the flag itself, but drone does not support that.
      - if [ "$DRONE_BUILD_EVENT" = "cron" ]; then EXTRA_FLAGS="--full"; fi
      - docker compose --project-name fsfe-website run --remove-orphans --build build --target "$TARGET" $EXTRA_FLAGS
    when:
      branch:
        - test
      event:
        exclude:
          - pull_request
trigger:
  branch:
    - master
    - test
  event:
    - cron
    - custom
    - pull_request
    - push

node:
  cont2: noris

volumes:
  # Define Docker socket of rootless docker user
  - name: dockersock
    host:
      path: /run/user/1001/docker.sock
---
kind: signature
hmac: 02de5f6b24fa72033e90a6058bde32e36716cbcbf207d56b6677c73be3a93d14
