kind: pipeline
type: docker
name: default

clone:
  depth: 150

steps:
  - name: syntaxcheck
    image: vsasyan/xmllint
    commands:
    - find . -type f \( -iname "*.xhtml" -o -iname "*.xml" -o -iname "*.xsl" \) -exec xmllint --noout {} +
    - bash tools/check-non-en-frontpage.sh news

trigger:
  branch:
  - master
  - test
  event:
  - push
  - pull_request
