services:
  build:
    build: .
    image: fsfe-websites
    container_name: fsfe-websites
    command:
    ports:
      - 2000:2000
      - 2100:2100
      - 2200:2200
      - 2300:2300
      - 2400:2400
      - 2500:2500
    environment:
      - SSH_KEY_1=${SSH_KEY_1:-none}
      - SSH_KEY_2=${SSH_KEY_2:-none}
      - SSH_KEY_3=${SSH_KEY_3:-none}
      - SSH_KEY_4=${SSH_KEY_4:-none}
    volumes:
      - website-cached:/website-cached
volumes:
  website-cached:
