services:
  build:
    build: .
    image: fsfe-websites
    container_name: fsfe-websites
    command:
    ports:
      - 2000:2000
      - 2100:2100
      - 2200:2200
      - 2300:2300
      - 2400:2400
      - 2500:2500
    environment:
      - KEY_PRIVATE=${KEY_PRIVATE:-none}
      - KEY_PASSWORD=${KEY_PASSWORD:-none}
    volumes:
      - website-cached:/website-cached
volumes:
  website-cached:
