#!/usr/bin/env bash
# Ran by dockerfile as entrypoint
# Ran from the volume of the website source mounted at /website-source

# Rsync files over, do nnot use the mtimes as they are wrong due to docker shenanigans
# Use the .gitignore as a filter to not remove any files generated by previous runs
rsync -az --delete --size-only --filter=':- .gitignore' ./ /website-cached/source

# Change to source repo
cd /website-cached/source  || exit 1

# run build script expaning all args passed to this script
python3 ./build.py "$@"


