#!/usr/bin/env bash
set -euo pipefail
# Ran by dockerfile as entrypoint
# Ran from the volume of the website source mounted at /website-source

# Rsync files over, do not use the mtimes as they are wrong due to docker shenanigans
# Use the .gitignore as a filter to not remove any files generated by previous runs
rsync -az --delete --checksum --filter=':- .gitignore' ./ /website-cached/source

# Change to source repo
cd /website-cached/source

# run build script expaning all args passed to this script
python3 ./build.py "$@"
