<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xsl:stylesheet [<!ENTITY nbsp "&#160;">
			  <!ENTITY eur "&#128;">]>

<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="html"
	    encoding="ISO-8859-1"
	    doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN"
	    doctype-system="http://www.w3.org/TR/REC-html40/loose.dtd"
	    indent="yes"
	    />

  <xsl:param name="fsffrance">http://france.fsfeurope.org</xsl:param>
  <xsl:param name="fsfeurope">http://www.fsfeurope.org</xsl:param>
  <xsl:param name="fsf">http://www.fsf.org</xsl:param>
  <xsl:param name="gnu">http://www.gnu.org</xsl:param>
  <xsl:param name="filebase">nofile.html</xsl:param>
  <xsl:param name="path">nofile.html</xsl:param>
  <xsl:param name="langlinks">[ English ]</xsl:param>

  <xsl:template match="/">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="/html/body">
    <body topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0" marginheight="0" marginwidth="0">
      <xsl:comment>

	DO NOT MODIFY THIS DOCUMENT. IT WAS GENERATED BY XSLT PROCESSING
	AND YOUR MODIFICATIONS WILL BE LOST. THE SOURCE OF THE DOCUMENT
	IS IN THE .xhtml FILE USE make all TO REGENERATE

      </xsl:comment>
      <xsl:apply-templates select="node()"/>
    </body>
  </xsl:template>

  <xsl:template match="/html/head">
    <head>
      <link rel="stylesheet" type="text/css" href="{$fsfeurope}/blue.css" />
      <xsl:apply-templates select="@*|node()"/>
    </head>
  </xsl:template>

  <xsl:include href="navigation.de.xsl" />
  <xsl:include href="navigation.cs.xsl" />
  <xsl:include href="navigation.en.xsl" />
  <xsl:include href="navigation.fr.xsl" />
  <xsl:include href="navigation.it.xsl" />
  <xsl:include href="navigation.pt.xsl" />
  <xsl:include href="navigation.es.xsl" />

  <xsl:template match="@*|node()" priority="-1">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>
