#!/usr/bin/env perl

# QA -- Tools to do quality assurance on static web pages.
#
# Copyright (C) 2010 Andreas Tolf Tolfsen <ato@fsfe.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;

use Data::Dumper;

use QA::Config;

while (my ($key, $value) = each(%{ $QA::Config->{modules} })) {
  my $module = ucfirst($value);
  eval "use QA::$module";
  #use QA::$module;
}

die;

use QA::Validation;

# Output

# Create list of all HTML files.
my @files = <../../*.html>;

my $validation = QA::Validation->new(files => \@files);
$validation->test;

