<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE xsl:stylesheet [<!ENTITY nbsp "&#160;">]>

<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="html"
	    encoding="ISO-8859-1"
	    doctype-public="-//W3C//DTD XHTML 1.0 Transitional//EN"
	    doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"
	    indent="yes"
	    />

  <xsl:param name="fsffrance">http://france.fsfeurope.org</xsl:param>
  <xsl:param name="fsfeurope">http://www.fsfeurope.org</xsl:param>
  <xsl:param name="fsf">http://www.fsf.org</xsl:param>
  <xsl:param name="gnu">http://www.gnu.org</xsl:param>

  <xsl:template match="/">
    <xsl:comment>
      DO NOT MODIFY THIS DOCUMENT. IT WAS GENERATED BY XSLT PROCESSING
      AND YOUR MODIFICATIONS WILL BE LOST. THE SOURCE OF THE DOCUMENT
      IS IN THE .xhtml FILE USE make all TO REGENERATE
    </xsl:comment>
    &nbsp;
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

  <xsl:template match="/html/head">
    <head>
      <link rel="stylesheet" type="text/css" href="{$fsffrance}/blue.css" />
      <xsl:apply-templates select="@*|node()"/>
    </head>
  </xsl:template>

  <xsl:include href="navigation.fr.xsl" />
  <xsl:include href="navigation.en.xsl" />

  <xsl:template match="@*|node()" priority="-1">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

</xsl:stylesheet>
