#!/bin/bash

# Find all files that have outdated translations or are untranslated.
# Usage: trans <language>
# Example: trans de
# Output is ordered: First all outdated translations, then all untranslated.
# Newest first.

# Written by Reinhard Mueller, mueller@fsfeurope.org
# This script is in the public domain.

# Get the date of a file. If somebody knows a better way, please tell me
getdate() {
  ls -l --full-time $1 | (read mode links owner group size rest; echo $rest) | sed -e "s% $1%%"
}

missing=""
outdated=""

# Ignore de fr etc. subdirectories, we don't need translations there
for orig in $(ls -t $(find ???* -name "*.en.xml") $(find ???* -name "*.en.xhtml")); do
  trans=${orig/%.en.xml/.$1.xml}
  trans=${trans/%.en.xhtml/.$1.xhtml}
  if [ ! -f ${trans} ]; then
    missing="${missing} ${trans}"
  elif [ ${trans} -ot ${orig} ]; then
    outdated="${outdated} ${trans}"
  fi
done

for i in ${outdated}; do
  orig=${i/%.$1.xml/.en.xml}
  orig=${orig/%.$1.xhtml/.en.xhtml}
  date=$(getdate $orig)
  echo "outdated since ${date}: $i"
done

for i in ${missing}; do
  orig=${i/%.$1.xml/.en.xml}
  orig=${orig/%.$1.xhtml/.en.xhtml}
  date=$(getdate $orig)
  echo "missing since ${date}: $i"
done
