# Sources for the website
[bootstrap]
repo = "https://github.com/twbs/bootstrap"
rev = "v3.0.3"
file_sets = [
  # { source = "dist/js/bootstrap.min.js", target = "scripts/thirdparty/bootstrap.min.js" },
]

[phpmailer]
repo = "https://github.com/PHPMailer/PHPMailer"
rev = "v6.10.0"
file_sets = [{ source = "src", target = "cgi-bin/thirdparty/PHPMailer" }]
