# Sources for the website
# SCRIPTS
[bootstrap]
repo = "https://github.com/twbs/bootstrap"
rev = "v3.0.3"
file_sets = [
  # { source = "dist/js/bootstrap.min.js", target = "scripts/thirdparty/bootstrap.min.js" },
]
[datatables]
repo = "https://github.com/DataTables/DataTables"
rev = "1.9.2"
file_sets = [{ source = ".", target = "scripts/thirdparty/data-tables" }]
[jquery]
repo = "https://github.com/jquery/jquery"
rev = "3.5.1"
file_sets = [
  { source = "dist/jquery.min.js", target = "scripts/thirdparty/" },
  { source = "dist/jquery.min.map", target = "scripts/thirdparty/" },
]
# STYLING
#
# CGI
[phpmailer]
repo = "https://github.com/PHPMailer/PHPMailer"
rev = "v6.10.0"
file_sets = [{ source = "src", target = "cgi-bin/thirdparty/PHPMailer" }]
