# Sources for the website
# SCRIPTS
# Actually, this one is scripts and styling
[bootstrap]
repo = "https://github.com/twbs/bootstrap"
rev = "v3.0.3"
file_sets = [
  # { source = "dist/js/bootstrap.min.js", target = "scripts/thirdparty/bootstrap.min.js" },
]
[datatables]
repo = "https://github.com/DataTables/DataTables"
rev = "1.9.2"
file_sets = [{ source = ".", target = "scripts/thirdparty/data-tables" }]
[jquery]
repo = "https://github.com/jquery/jquery"
rev = "3.5.1"
file_sets = [
  { source = "dist/jquery.min.js", target = "scripts/thirdparty/" },
  { source = "dist/jquery.min.map", target = "scripts/thirdparty/" },
]
[jquery-localization]
repo = "https://github.com/jquery-validation/jquery-validation"
rev = "1.21.0"
file_sets = [
  { source = "src/localization", target = "scripts/thirdparty/jquery.validate-localization" },
]
[lunr]
repo = "https://github.com/olivernn/lunr.js"
rev = "v2.3.9"
file_sets = [{ source = "lunr.js", target = "scripts/thirdparty/lunr.min.js" }]
# STYLING
#
# CGI
[phpmailer]
repo = "https://github.com/PHPMailer/PHPMailer"
rev = "v6.10.0"
file_sets = [{ source = "src", target = "cgi-bin/thirdparty/PHPMailer" }]
